"use client";

import Link from "next/link";
import { type FormEvent as ReactFormEvent, type PointerEvent as ReactPointerEvent, useActionState, useEffect, useMemo, useRef, useState, useTransition } from "react";
import { assignDeckFolderAction, copyDeckAction, createDeckFolderAction, createFolderAndAssignDeckAction, deleteDeckAction, deleteDeckFolderAction, moveDeckToFolderAction, renameDeckAction, renameDeckFolderAction, reorderDeckFoldersAction, reorderDecksAction, setDeckIconAction, setDeckListSortAction, toggleDeckVisibilityAction } from "@/app/decks/actions";
import { initialDeckActionState } from "@/app/decks/action-state";
import { CardArtwork } from "@/components/card-artwork";
import { DeckPreviewModal } from "@/components/deck-preview-modal";

export type DeckListSortMode = "user" | "newest";
export type DeckListItem = { id:string; name:string; format:string; visibility:string; description:string; createdAt:string; updatedAt:string; folderId:string|null; userSortOrder:number; count:number; imageUrl:string|null; iconChoices:{canonicalCardId:number;name:string;imageUrl:string|null}[] };
export type DeckFolder = { id:string; name:string; userSortOrder:number };
type DragItem = { kind:"folder"; id:string } | { kind:"deck"; id:string; folderId:string|null };
type ActiveDrag = DragItem & { active:boolean; captureTarget:HTMLElement|null; changed:boolean; before:string[]; dropFolderId:string|null; pointerId:number; startX:number; startY:number; scrolling:boolean; timer:ReturnType<typeof setTimeout>|null };
type FolderDialog = { folder:DeckFolder; kind:"rename"|"delete" };

function moveId(ids:string[],sourceId:string,targetId:string){const source=ids.indexOf(sourceId),target=ids.indexOf(targetId);if(source<0||target<0||source===target)return ids;const next=[...ids];next.splice(source,1);next.splice(target,0,sourceId);return next;}
function formatName(format:string){return format==="advanced"?"アドバンス":format==="duel_party"?"デュエパーティ":"オリジナル";}

function DeckFolderDialog({dialog,onClose,onSuccess}:{dialog:FolderDialog;onClose:()=>void;onSuccess:(message:string)=>void}){
 const action=dialog.kind==="rename"?renameDeckFolderAction:deleteDeckFolderAction;
 const[state,formAction,pending]=useActionState(action,initialDeckActionState);
 const[name,setName]=useState(dialog.folder.name);
 useEffect(()=>{if(state.status==="success")onSuccess(state.message);},[onSuccess,state]);
 useEffect(()=>{const handleKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();};document.addEventListener("keydown",handleKeyDown);return()=>document.removeEventListener("keydown",handleKeyDown);},[onClose]);
 return <div className="deck-actions-backdrop" onPointerDown={event=>{if(event.target===event.currentTarget)onClose();}}><section aria-modal="true" aria-labelledby="deck-folder-dialog-title" className="deck-actions-modal deck-folder-actions-modal" role="dialog"><header><strong id="deck-folder-dialog-title">{dialog.kind==="rename"?"フォルダ名を変更":"フォルダを削除"}</strong><button aria-label="閉じる" onClick={onClose} type="button">×</button></header>{dialog.kind==="rename"?<form action={formAction} className="deck-folder-edit-form"><input name="folderId" type="hidden" value={dialog.folder.id}/><label>フォルダ名<input autoFocus maxLength={60} name="name" onChange={event=>setName(event.target.value)} required value={name}/></label><button disabled={pending} type="submit">{pending?"変更中…":"変更"}</button></form>:<form action={formAction} className="deck-folder-delete-form"><input name="folderId" type="hidden" value={dialog.folder.id}/><p>「{dialog.folder.name}」を削除します。所属デッキは削除されず、未分類へ移動します。</p><button className="danger" disabled={pending} type="submit">{pending?"削除中…":"フォルダを削除"}</button></form>}{state.status==="error"?<p className="notice error deck-folder-action-error" role="alert">{state.message}</p>:null}</section></div>;
}

function DeckNameEditor({deck,onRename}:{deck:DeckListItem;onRename:(id:string,name:string)=>void}){
 const[editing,setEditing]=useState(false);
 const[name,setName]=useState(deck.name);
 const[error,setError]=useState("");
 const[pending,startTransition]=useTransition();
 function cancel(){setName(deck.name);setError("");setEditing(false);}
 function submit(event:ReactFormEvent<HTMLFormElement>){
  event.preventDefault();
  if(pending)return;
  const normalizedName=name.trim();
  if(!normalizedName||normalizedName.length>60){setError("デッキ名は1〜60文字で入力してください。");return;}
  const formData=new FormData();formData.set("deckId",deck.id);formData.set("name",normalizedName);
  setError("");
  startTransition(async()=>{const result=await renameDeckAction(formData);if(result.status==="success"){onRename(deck.id,normalizedName);setEditing(false);}else setError(result.message);});
 }
 return <div className="deck-name-editor">{editing?<form onSubmit={submit}><input aria-label="デッキ名" autoFocus maxLength={60} onChange={event=>setName(event.target.value)} required value={name}/><button disabled={pending} type="submit">{pending?"変更中…":"保存"}</button><button disabled={pending} onClick={cancel} type="button">キャンセル</button>{error?<span role="alert">{error}</span>:null}</form>:<><strong>{deck.name}</strong><button aria-label={`${deck.name}の名前を変更`} onClick={()=>setEditing(true)} title="デッキ名を変更" type="button"><span aria-hidden="true" className="ui-icon ui-icon-edit"/></button></>}</div>;
}

export function MyDecksBrowser({decks,folders,initialSortMode,initialUnfiledFolderSortOrder}:{decks:DeckListItem[];folders:DeckFolder[];initialSortMode:DeckListSortMode;initialUnfiledFolderSortOrder:number}){
 const initialFolderOrder=[...folders.map(folder=>({id:folder.id,sortOrder:folder.userSortOrder,name:folder.name})),{id:"none",sortOrder:initialUnfiledFolderSortOrder,name:"未分類"}].toSorted((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name,"ja")).map(folder=>folder.id);
 const initialDeckOrder=decks.toSorted((a,b)=>a.userSortOrder-b.userSortOrder||a.id.localeCompare(b.id)).map(deck=>deck.id);
 const[query,setQuery]=useState("");const[sortMode,setSortMode]=useState<DeckListSortMode>(initialSortMode);const[folderOrder,setFolderOrder]=useState(initialFolderOrder);const[deckOrder,setDeckOrder]=useState(initialDeckOrder);const[expanded,setExpanded]=useState(()=>new Set<string>(initialFolderOrder));
  const[selected,setSelected]=useState<DeckListItem|null>(null);const[renamedNames,setRenamedNames]=useState<Record<string,string>>({});const[previewDeck,setPreviewDeck]=useState<DeckListItem|null>(null);const[folderDialog,setFolderDialog]=useState<FolderDialog|null>(null);const[iconDeck,setIconDeck]=useState<DeckListItem|null>(null);const[showFolderForm,setShowFolderForm]=useState(false);const[showModalFolderForm,setShowModalFolderForm]=useState(false);const[shareDone,setShareDone]=useState(false);const[dragging,setDragging]=useState<DragItem|null>(null);const[dropFolderId,setDropFolderId]=useState<string|null>(null);const[deckFolders,setDeckFolders]=useState<Record<string,string|null>>({});const[reorderMessage,setReorderMessage]=useState("");const[,startTransition]=useTransition();
 const dragRef=useRef<ActiveDrag|null>(null),folderOrderRef=useRef(folderOrder),deckOrderRef=useRef(deckOrder),suppressClickUntilRef=useRef(0);
 const deckById=useMemo(()=>new Map(decks.map(deck=>[deck.id,deck])),[decks]);const folderById=useMemo(()=>new Map(folders.map(folder=>[folder.id,folder])),[folders]);const normalizedQuery=query.trim().toLocaleLowerCase("ja-JP");
  const groups=useMemo(()=>{const folderGroups=folderOrder.map(id=>id==="none"?{id,name:"未分類",isFolder:false}:(()=>{const folder=folderById.get(id);return folder?{id:folder.id,name:folder.name,isFolder:true}:null;})()).filter((group):group is {id:string;name:string;isFolder:boolean}=>Boolean(group));const userOrder=new Map(deckOrder.map((id,index)=>[id,index]));return folderGroups.map(group=>({...group,items:decks.filter(deck=>(deckFolders[deck.id]===undefined?deck.folderId:deckFolders[deck.id])===(group.id==="none"?null:group.id)).filter(deck=>!normalizedQuery||(renamedNames[deck.id]??deck.name).toLocaleLowerCase("ja-JP").includes(normalizedQuery)).toSorted((left,right)=>sortMode==="newest"?Date.parse(right.createdAt)-Date.parse(left.createdAt):(userOrder.get(left.id)??Number.MAX_SAFE_INTEGER)-(userOrder.get(right.id)??Number.MAX_SAFE_INTEGER))})).filter(group=>!normalizedQuery||group.items.length>0);},[deckOrder,deckFolders,decks,folderById,folderOrder,normalizedQuery,renamedNames,sortMode]);
 useEffect(()=>{const blockScrollWhileDragging=(event:TouchEvent)=>{if(dragRef.current?.active)event.preventDefault();};document.addEventListener("touchmove",blockScrollWhileDragging,{passive:false});return()=>document.removeEventListener("touchmove",blockScrollWhileDragging);},[]);
 function isInteractiveTarget(target:EventTarget|null){return target instanceof Element&&Boolean(target.closest("button,a,input,select,textarea,label"));}
 function toggleFolder(id:string){if(Date.now()<suppressClickUntilRef.current)return;setExpanded(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});}
 function releasePointerCapture(current:ActiveDrag){if(!current.captureTarget)return;try{if(current.captureTarget.hasPointerCapture(current.pointerId))current.captureTarget.releasePointerCapture(current.pointerId);}catch{}current.captureTarget=null;}
  function beginLongPress(event:ReactPointerEvent<HTMLElement>,item:DragItem){const folderToggle=item.kind==="folder"&&event.target instanceof Element&&Boolean(event.target.closest(".deck-folder-toggle"));if(!event.isPrimary||event.button!==0||(isInteractiveTarget(event.target)&&!folderToggle))return;if(item.kind==="deck"&&(sortMode!=="user"||normalizedQuery)){setReorderMessage("デッキの並び替えは「ユーザー設定順」で検索を解除すると利用できます。");return;}const before=item.kind==="folder"?[...folderOrderRef.current]:[...deckOrderRef.current],captureTarget=event.currentTarget;const pending:ActiveDrag={...item,active:false,captureTarget:null,changed:false,before,dropFolderId:null,pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,scrolling:false,timer:null};pending.timer=setTimeout(()=>{if(dragRef.current!==pending)return;pending.active=true;pending.captureTarget=captureTarget;try{captureTarget.setPointerCapture(pending.pointerId);}catch{pending.captureTarget=null;}setDragging(item);setReorderMessage(item.kind==="folder"?"フォルダを移動中です。":"デッキを移動中です。");},450);dragRef.current=pending;}
  function moveLongPress(event:ReactPointerEvent<HTMLElement>){const current=dragRef.current;if(!current||current.pointerId!==event.pointerId)return;if(!current.active&&Math.hypot(event.clientX-current.startX,event.clientY-current.startY)>10){if(current.timer)clearTimeout(current.timer);current.scrolling=event.pointerType==="touch";}if(current.scrolling)return;if(!current.active)return;event.preventDefault();const hit=document.elementFromPoint(event.clientX,event.clientY);if(current.kind==="deck"){const group=hit?.closest<HTMLElement>('.deck-folder-group');const folderId=group?.dataset.reorderId??null;const destination=folderId&&folderId!==(current.folderId??"none")?folderId:null;if(current.dropFolderId!==destination){current.dropFolderId=destination;setDropFolderId(destination);}if(destination)return;}const target=hit?.closest<HTMLElement>(`[data-reorder-kind="${current.kind}"]`),targetId=target?.dataset.reorderId;if(!targetId||targetId===current.id)return;if(current.kind==="folder"){const next=moveId(folderOrderRef.current,current.id,targetId);if(next===folderOrderRef.current)return;current.changed=true;folderOrderRef.current=next;setFolderOrder(next);return;}if((target.dataset.folderId||"none")!==(current.folderId||"none"))return;const next=moveId(deckOrderRef.current,current.id,targetId);if(next===deckOrderRef.current)return;current.changed=true;deckOrderRef.current=next;setDeckOrder(next);}
  function endLongPress(event:ReactPointerEvent<HTMLElement>){const current=dragRef.current;if(!current||current.pointerId!==event.pointerId)return;if(current.timer)clearTimeout(current.timer);if(current.active)moveLongPress(event);dragRef.current=null;releasePointerCapture(current);if(current.scrolling){suppressClickUntilRef.current=Date.now()+250;return;}if(!current.active)return;event.preventDefault();suppressClickUntilRef.current=Date.now()+250;setDragging(null);setDropFolderId(null);if(current.kind==="deck"&&current.dropFolderId){const destination=current.dropFolderId;const beforeOrder=[...current.before];const nextOrder=[...beforeOrder.filter(id=>id!==current.id),current.id];deckOrderRef.current=nextOrder;setDeckOrder(nextOrder);setDeckFolders(previous=>({...previous,[current.id]:destination==="none"?null:destination}));const formData=new FormData();formData.set("deckId",current.id);formData.set("folderId",destination==="none"?"":destination);startTransition(async()=>{const result=await moveDeckToFolderAction(formData);if(!result.ok){deckOrderRef.current=beforeOrder;setDeckOrder(beforeOrder);setDeckFolders(previous=>{const next={...previous};delete next[current.id];return next;});setReorderMessage("デッキを移動できませんでした。");}else setReorderMessage("デッキを移動しました。");});return;}if(!current.changed)return;const formData=new FormData();if(current.kind==="folder"){formData.set("orderedIds",JSON.stringify(folderOrderRef.current));startTransition(async()=>{const result=await reorderDeckFoldersAction(formData);if(!result.ok){folderOrderRef.current=current.before;setFolderOrder(current.before);setReorderMessage("フォルダの並び順を保存できませんでした。");}else setReorderMessage("フォルダの並び順を保存しました。");});return;}const groupIds=deckOrderRef.current.filter(id=>(deckFolders[id]===undefined?deckById.get(id)?.folderId:deckFolders[id])===current.folderId);formData.set("orderedIds",JSON.stringify(groupIds));formData.set("folderId",current.folderId??"");startTransition(async()=>{const result=await reorderDecksAction(formData);if(!result.ok){deckOrderRef.current=current.before;setDeckOrder(current.before);setReorderMessage("デッキの並び順を保存できませんでした。");}else setReorderMessage("デッキの並び順を保存しました。");});}
  function cancelLongPress(event:ReactPointerEvent<HTMLElement>){const current=dragRef.current;if(!current||current.pointerId!==event.pointerId)return;if(current.timer)clearTimeout(current.timer);releasePointerCapture(current);if(current.active){if(current.kind==="folder"){folderOrderRef.current=current.before;setFolderOrder(current.before);}else{deckOrderRef.current=current.before;setDeckOrder(current.before);}}dragRef.current=null;setDragging(null);setDropFolderId(null);}
 function changeSortMode(mode:DeckListSortMode){setSortMode(mode);setReorderMessage(mode==="user"?"押し続けてデッキを並び替えできます。":"この並び順をアカウントに保存しました。ユーザー設定順は保持されます。");const formData=new FormData();formData.set("mode",mode);startTransition(async()=>{const result=await setDeckListSortAction(formData);if(!result.ok){setSortMode(initialSortMode);setReorderMessage("並び順の設定を保存できませんでした。");}});}
 return <div className="my-decks-browser">
  <div className="my-decks-filters"><label><span aria-hidden="true">⌕</span><input aria-label="デッキ名で検索" onChange={event=>setQuery(event.target.value)} placeholder="デッキ名で検索" value={query}/></label><select aria-label="デッキの並び順" onChange={event=>changeSortMode(event.target.value as DeckListSortMode)} value={sortMode}><option value="user">ユーザー設定順</option><option value="newest">新規順</option></select><button onClick={()=>setShowFolderForm(visible=>!visible)} type="button"><span aria-hidden="true" className="add-folder-icon"/> フォルダ追加</button></div>
  {showFolderForm?<form action={createDeckFolderAction} className="deck-folder-form"><input autoFocus maxLength={60} name="name" placeholder="新しいフォルダ名" required/><button type="submit">作成</button></form>:null}<p aria-live="polite" className="deck-reorder-help">{reorderMessage||"フォルダとデッキは押し続けて並び替えできます。"}</p>
   <div className="deck-folder-list">{groups.map(group=><section className={`deck-folder-group ${dragging?.kind==="folder"&&dragging.id===group.id?"is-dragging":""} ${dropFolderId===group.id?"is-drop-target":""}`} data-reorder-id={group.id} data-reorder-kind="folder" key={group.id} onContextMenu={event=>event.preventDefault()} onPointerCancel={cancelLongPress} onPointerDown={event=>beginLongPress(event,{kind:"folder",id:group.id})} onPointerMove={moveLongPress} onPointerUp={endLongPress}>
   <div className="deck-folder-heading"><button aria-expanded={expanded.has(group.id)} className="deck-folder-toggle" onClick={()=>toggleFolder(group.id)} type="button"><span aria-hidden="true">{expanded.has(group.id)?"▼":"▶"}</span><strong>{group.name}</strong><small>（{group.items.length}）</small></button>{group.isFolder?<div className="deck-folder-actions"><button aria-label={`${group.name}の名前を変更`} className="deck-folder-action deck-folder-rename" onClick={event=>{event.stopPropagation();const folder=folderById.get(group.id);if(folder)setFolderDialog({folder,kind:"rename"});}} onPointerDown={event=>event.stopPropagation()} title="フォルダ名を変更" type="button"><span aria-hidden="true" className="ui-icon ui-icon-edit"/></button><button aria-label={`${group.name}を削除`} className="deck-folder-action deck-folder-delete" onClick={event=>{event.stopPropagation();const folder=folderById.get(group.id);if(folder)setFolderDialog({folder,kind:"delete"});}} onPointerDown={event=>event.stopPropagation()} title="フォルダを削除" type="button"><span aria-hidden="true" className="ui-icon ui-icon-trash"/></button></div>:null}</div>
    {expanded.has(group.id)?<div className="my-decks-list">{group.items.map(deck=><article aria-label={`${deck.name}を確認`} className={`my-deck-row ${sortMode==="user"&&!normalizedQuery?"can-reorder":""} ${dragging?.kind==="deck"&&dragging.id===deck.id?"is-dragging":""}`} data-folder-id={group.id} data-reorder-id={deck.id} data-reorder-kind="deck" key={deck.id} onClick={()=>{if(Date.now()>=suppressClickUntilRef.current)setPreviewDeck(deck);}} onContextMenu={event=>event.preventDefault()} onKeyDown={event=>{if((event.key==="Enter"||event.key===" ")&&event.target===event.currentTarget){event.preventDefault();setPreviewDeck(deck);}}} onPointerCancel={event=>{event.stopPropagation();cancelLongPress(event);}} onPointerDown={event=>{event.stopPropagation();beginLongPress(event,{kind:"deck",id:deck.id,folderId:group.id==="none"?null:group.id});}} onPointerMove={event=>{event.stopPropagation();moveLongPress(event);}} onPointerUp={event=>{event.stopPropagation();endLongPress(event);}} role="button" tabIndex={0}><button aria-label={`${deck.name}のアイコンを変更`} className="my-deck-icon-button" onClick={event=>{event.stopPropagation();if(Date.now()>=suppressClickUntilRef.current)setIconDeck(deck);}} onPointerDown={event=>event.stopPropagation()} type="button"><CardArtwork className="my-deck-thumbnail" eager fit="cover" imageUrl={deck.imageUrl} name={deck.name} sizes="110px"/></button><span className="my-deck-details-button"><span className="my-deck-info"><strong>{renamedNames[deck.id]??deck.name}</strong><span className="my-deck-badges"><em>{formatName(deck.format)}</em><em>{deck.count}枚</em></span><span className="my-deck-counts">メイン {deck.count} / GR 0 / 超次元 0</span></span></span><Link aria-label={`${deck.name}を編集`} className="my-deck-edit" href={`/decks/${deck.id}/edit`} onClick={event=>event.stopPropagation()} onPointerDown={event=>event.stopPropagation()}><span aria-hidden="true" className="ui-icon ui-icon-edit"/>編集</Link><button aria-label={`${deck.name}のメニューを開く`} className="my-deck-more" onClick={event=>{event.stopPropagation();setSelected(deck);}} onPointerDown={event=>event.stopPropagation()} type="button">・・・</button></article>)}</div>:null}
  </section>)}</div>{!decks.length?<div className="history-empty"><strong>デッキがありません</strong><p>新しいデッキを作成してください。</p></div>:null}<Link aria-label="新しいデッキを作成" className="floating-deck-create" href="/decks/new"><span aria-hidden="true">＋</span>デッキ作成</Link>
  {previewDeck?<DeckPreviewModal deckId={previewDeck.id} deckName={previewDeck.name} onClose={()=>setPreviewDeck(null)} scope="mine"/>:null}
  {folderDialog?<DeckFolderDialog dialog={folderDialog} key={`${folderDialog.kind}:${folderDialog.folder.id}`} onClose={()=>setFolderDialog(null)} onSuccess={message=>{setFolderDialog(null);setReorderMessage(message);}}/>:null}
  {iconDeck?<div className="deck-actions-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setIconDeck(null);}}><section aria-modal="true" className="deck-icon-modal" role="dialog"><header><div><strong>デッキアイコンを選択</strong><small>{iconDeck.name}に含まれるカード</small></div><button aria-label="閉じる" onClick={()=>setIconDeck(null)} type="button">×</button></header><div className="deck-icon-choices">{iconDeck.iconChoices.map(choice=><form action={setDeckIconAction} key={choice.canonicalCardId}><input name="deckId" type="hidden" value={iconDeck.id}/><input name="canonicalCardId" type="hidden" value={choice.canonicalCardId}/><button title={choice.name} type="submit"><CardArtwork imageUrl={choice.imageUrl} name={choice.name} sizes="110px"/><span>{choice.name}</span></button></form>)}</div>{!iconDeck.iconChoices.length?<p>アイコンに選べるカードがありません。</p>:null}</section></div>:null}
  {selected?<div className="deck-actions-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null);}}><section aria-modal="true" className="deck-actions-modal" role="dialog"><header><DeckNameEditor deck={selected} key={selected.id} onRename={(id,name)=>{setRenamedNames(current=>({...current,[id]:name}));setSelected(current=>current?.id===id?{...current,name}:current);}}/><button aria-label="閉じる" onClick={()=>setSelected(null)} type="button">×</button></header><div className="deck-action-grid"><form action={copyDeckAction}><input name="deckId" type="hidden" value={selected.id}/><button type="submit"><span aria-hidden="true">▣</span><span className="deck-action-label">コピー</span></button></form><Link href={`/playtest/${selected.id}/opponent`}><span aria-hidden="true" className="ui-icon ui-icon-my-decks"/><span className="deck-action-label">ひとり回し</span></Link><form action={deleteDeckAction}><input name="deckId" type="hidden" value={selected.id}/><button className="danger" type="submit"><span aria-hidden="true" className="ui-icon ui-icon-trash"/><span className="deck-action-label">削除</span></button></form></div><form action={assignDeckFolderAction} className="deck-folder-select-row"><input name="deckId" type="hidden" value={selected.id}/><select aria-label="含めるフォルダ" defaultValue={selected.folderId??""} name="folderId"><option value="">未分類</option>{folders.map(folder=><option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><button type="submit">変更</button></form><button className="folder-create-assign" onClick={()=>setShowModalFolderForm(visible=>!visible)} type="button">＋ フォルダ新規作成＆デッキ追加</button>{showModalFolderForm?<form action={createFolderAndAssignDeckAction} className="modal-folder-create"><input name="deckId" type="hidden" value={selected.id}/><input autoFocus maxLength={60} name="name" placeholder="新しいフォルダ名" required/><button type="submit">作成して追加</button></form>:null}<button className="deck-share-button" onClick={async()=>{await navigator.clipboard.writeText(`${window.location.origin}/playtest/${selected.id}`);setShareDone(true);}} type="button">⌯　{shareDone?"URLをコピーしました":"デッキを共有"}</button><form action={toggleDeckVisibilityAction} className="deck-modal-row"><input name="deckId" type="hidden" value={selected.id}/><input name="visibility" type="hidden" value={selected.visibility==="public"?"private":"public"}/><span>デッキ公開</span><button aria-label="公開状態を切り替え" className={selected.visibility==="public"?"toggle active":"toggle"} type="submit"><i/></button></form></section></div>:null}
 </div>;
}
